### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by Cosmysd** [iIIusi0n/Cloudflare-Bypass-Script#8]
Hello sir @wyvernnet  your script look patched, u have to do some changes to update
1. change main script in solve hcaptcha file, replace  with this one https://assets.hcaptcha.com/c/7f492a3/hsl.js
2. using onother browser for bypass, phantomjs /chromedp/Geckodriver (using selenium maybe)
3. Best choice is to improve it using 2captcha  (can bypass more type of captchas)

**Comment by okinats** [comment]
hi @Cosmysd, can i get your  contact?

**Comment by Cosmysd** [comment]
> hi @Cosmysd, can i get your contact?

email :  Alex.aleco@protonmail.com

**Comment by iIIusi0n** [comment]
I dont have time to work on this project.
If u can, make pull request and i will accept them.
